In [1]:
from wikipedia2vec import Wikipedia2Vec

In [5]:
# load .txt data
# data = open('../datasets/enwiki_20180420_100d.txt', 'r')

# print('start reading.')

# content = data.read()

# print('read content')

# import pickle

# pickleFile = open('pickleWikipediaWords', 'ab')

# print('start dumping')

# pickle.dump(content, pickleFile)

# print('dumped to pickle file.')

# pickleFile.close()
# data.close()


In [3]:
wiki2vec = Wikipedia2Vec.load("../datasets/enwiki_20180420_100d.pkl")
print(wiki2vec.get_word_vector("account"))
wiki2vec.most_similar(wiki2vec.get_word('nail'),10)

/home/bob/anaconda3/envs/code/lib/python3.9/site-packages/joblib/numpy_pickle.py:230: UserWarning: The memmapped array [[-0.12560804 -0.5235532  -0.13231167 ... -0.48633438  0.45111445
   0.11309847]
 [-0.12473089 -0.6455471   0.13622157 ... -0.6347396   0.5410465
   0.32159257]
 [-0.05129661 -0.4987064  -0.09563554 ... -0.30148467  0.24280211
  -0.08308805]
 ...
 [-1.0583687  -0.83086014 -0.4427682  ... -1.0160557  -0.02469787
   0.99688977]
 [-1.0772408  -0.32139003 -0.79673034 ... -1.3150353  -0.12155519
   0.57841384]
 [-0.86319923 -0.5425662  -0.5506818  ... -1.1069874   0.26995388
   0.43403685]] loaded from the file ../datasets/enwiki_20180420_100d.pkl is not not bytes aligned. This may cause segmentation faults if this memmapped array is used in some libraries like BLAS or PyTorch. To get rid of this warning, regenerate your pickle file with joblib >= 1.2.0. See https://github.com/joblib/joblib/issues/563 for more details
  warnings.warn(message)
/home/bob/anaconda3/envs/code/l

[ 0.26157779 -0.06324237  0.01413879  0.3471325  -0.03113616  0.04367286
  0.16051093  0.13918966  0.4020053   0.02132417  0.4937738  -0.19357482
  0.16570787  0.20006967  0.46038646  0.11534599 -0.07132792  0.06508564
  0.33278874 -0.3134719   0.23085992 -0.34622437  0.03082101  0.506029
 -0.45648044 -0.16179349 -0.55180806 -0.48477042  0.39876133  0.35310695
 -0.02152728 -0.09419352  0.3356566   0.7128895  -0.16417094 -0.21861316
  0.23070154  0.420371    0.08505379  0.22867164 -0.10435292 -0.23085395
 -0.5007337   0.32013428  0.06766731  0.25432208 -0.19289295  0.32780027
 -0.27101117  0.29084572  0.12556057 -0.06193651  0.16854699  0.58460623
  0.11538803  0.0525699  -0.17319302  0.17267288  0.00414904  0.2039684
 -0.19071926 -0.251641    0.06552824  0.2605905   0.5945521  -0.6533295
 -0.32521802 -0.3095794  -0.30898058 -0.3941069   0.04687437  0.3577981
  0.12849359  0.3052618  -0.26543605  0.51226574 -0.12460668  0.2912351
 -0.06106061 -0.30229414 -0.4071444  -0.48364484  0.26128

[ItemWithScore(item=<Word nail>, score=1.0),
 ItemWithScore(item=<Word hurriquake>, score=0.7744725942611694),
 ItemWithScore(item=<Word nails>, score=0.7489219307899475),
 ItemWithScore(item=<Word fingernails>, score=0.7278966307640076),
 ItemWithScore(item=<Word toenail>, score=0.7257317900657654),
 ItemWithScore(item=<Word shoe>, score=0.714025616645813),
 ItemWithScore(item=<Word hoof>, score=0.7137674689292908),
 ItemWithScore(item=<Word glue>, score=0.7104105949401855),
 ItemWithScore(item=<Word fingernail>, score=0.7092493772506714),
 ItemWithScore(item=<Word splint>, score=0.7087520956993103)]

In [12]:
# define nouns 
nouns= [
    "man",
    'woman',
    'person',
    'dinner',
    'meal',
    'sauce',
    'program',
    "application",
    "software"
]

In [16]:
# from pprint import pprint
import numpy as np

vecs = []
for noun in nouns:
    if noun == "charge_n":
        vecs.append(wiki2vec.get_word_vector("charge").tolist())
    else:
        vecs.append(wiki2vec.get_word_vector(noun).tolist())
vecs = np.array(vecs)

In [14]:
print(np.shape(vecs))

(9, 100)


In [17]:
# do PCA 
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
vecs_new = pca.fit_transform(vecs)
print(pca.explained_variance_ratio_)

[0.35410539 0.26345813 0.15045848 0.06934345]


In [9]:
print(np.shape(vecs_new))

print(vecs_new)

(5, 4)
[[ 0.66429603 -0.54404025  1.49939577 -0.98605524]
 [ 1.91903733 -0.25475082 -1.35628697 -0.22165542]
 [-1.10981432  2.05853645 -0.28236348 -0.4811538 ]
 [-1.89954249 -1.57877889 -0.53063466  0.07442904]
 [ 0.42602345  0.31903351  0.66988934  1.61443542]]


In [18]:
sum_of_rows = np.linalg.norm(vecs_new,axis=1)
normalized_array = vecs_new / sum_of_rows[:, np.newaxis]

new_noun_vectors = {}
for i, noun in enumerate(nouns):
   new_noun_vectors[noun] = normalized_array[i].tolist()

In [19]:
print(new_noun_vectors)

{'man': [-0.2370557742915931, 0.8594845323830477, 0.3846999454317827, 0.23894947259638483], 'woman': [-0.27951714077436546, 0.935316671360229, 0.19839348423523656, 0.08770927945176635], 'person': [-0.5346517001188761, 0.6661434501746717, 0.2699187981144731, -0.4444595659605252], 'dinner': [0.6136596314966611, 0.19067233708423176, -0.7235016261132731, -0.2522128338401291], 'meal': [0.8054883467263027, -0.09811703566160111, -0.5492470411677177, -0.199722954037874], 'sauce': [0.8385219988829802, -0.272232903723701, 0.4566207580609005, 0.11944700426273665], 'program': [-0.46350928959134563, -0.24974397395730483, -0.5136348749891828, 0.6774705167971413], 'application': [-0.6637098891095032, -0.7318362754419938, 0.041285636954133134, -0.148997802758069], 'software': [-0.6244912758334976, -0.7379779308107106, 0.19104097608762097, -0.17000754541984703]}
